### ISSUE TITLE
Push jobs not configured in all environments

### ISSUE THREAD

**Issue by tpetchel** [chef-cft/wombat#133]
In my `wombat.yml`, I specify 4 environments:

```
infranodes:
  acceptance: []
  union: []
  rehearsal: []
  delivered: []
```

`knife node status` only reports 3 of them; `delivered` doesn't show.

```
C:\Users\Administrator\delivery-demo\awesome_customers_delivery [master ≡]> knife node status
acceptance      available
build-node-1    available
build-node-2    available
rehearsal       available
union   available
```

```
C:\Users\Administrator\delivery-demo\awesome_customers_delivery [master ≡]> knife node status delivered
delivered       unavailable
```

I will investigate more, but wanted to get this one on the board.
