### ISSUE TITLE
CFN template contains invalid AMI IDs

### ISSUE THREAD

**Issue by tpetchel** [chef-cft/wombat#96]
After running `rake cfn:create_template`, my CFN template file, wombat.json, contains a few invalid AMI IDs. Note the entries containing "Builds" instead of an AMI ID.

```
    "ChefServerAMI": {
      "Type": "String",
      "Default": "Builds",
      "Description": "AMI ID for the Chef Server"
    },
    "DeliveryServerAMI": {
      "Type": "String",
      "Default": "ami-1317d273",
      "Description": "AMI ID for the Delivery Server"
    },
    "ComplianceServerAMI": {
      "Type": "String",
      "Default": "Builds",
      "Description": "AMI ID for the Delivery Server"
    },
    "BuildNode1AMI": {
      "Type": "String",
      "Default": "ami-320ecb52",
      "Description": "AMI ID for Build Node 1"
    },
    "WindowsWorkstationAMI": {
      "Type": "String",
      "Default": "ami-7017d210",
      "Description": "AMI ID for the Windows Workstation"
    }
```

This of course causes failures when you run the CFN template.

```
14:42:50 UTC-0400   CREATE_FAILED   AWS::EC2::Instance  ChefServer  Invalid id: "Builds" (expecting "ami-...")
14:42:50 UTC-0400   CREATE_COMPLETE AWS::EC2::NetworkAclEntry   InboundNetworkAclEntry  
14:42:50 UTC-0400   CREATE_FAILED   AWS::EC2::Instance  ComplianceServer    Invalid id: "Builds" (expecting "ami-...")
```

Here's my wombat.yml file:

```

---
name: wombat
domain: chordata.biz
enterprise: mammalia
org: diprotodontia
build-nodes: '1'
infranodes:
  acceptance:
  delivered:
version: 0.0.12
products:
  chef-server: 12.6.0
  chefdk: 0.14.25
  #compliance: 1.3.1
  delivery: 0.4.404
aws:
  region: us-east-1
  az: us-east-1c
  keypair: tpetchel-mktg
```

I'm looking into what caused this, but wanted to at least get the issue on the board.
